// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCImAInmVS1KUItC3AHVZkGhqQehv_c7bY',
    appId: '1:648534161256:web:25504272ac7baf346948dd',
    messagingSenderId: '648534161256',
    projectId: 'crm-project-f8f9c',
    authDomain: 'crm-project-f8f9c.firebaseapp.com',
    storageBucket: 'crm-project-f8f9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD4a3rbkFJUD3OmhohOun0iHWjeJSxEoI',
    appId: '1:648534161256:android:a1d65d3125bcef986948dd',
    messagingSenderId: '648534161256',
    projectId: 'crm-project-f8f9c',
    storageBucket: 'crm-project-f8f9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6-ryuu9AvCpJxIGDcTd_AaJpXVmK767w',
    appId: '1:648534161256:ios:a59bfd2341f2fd236948dd',
    messagingSenderId: '648534161256',
    projectId: 'crm-project-f8f9c',
    storageBucket: 'crm-project-f8f9c.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6-ryuu9AvCpJxIGDcTd_AaJpXVmK767w',
    appId: '1:648534161256:ios:a59bfd2341f2fd236948dd',
    messagingSenderId: '648534161256',
    projectId: 'crm-project-f8f9c',
    storageBucket: 'crm-project-f8f9c.firebasestorage.app',
    iosBundleId: 'com.example.crm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCImAInmVS1KUItC3AHVZkGhqQehv_c7bY',
    appId: '1:648534161256:web:e6e0808c26dec8366948dd',
    messagingSenderId: '648534161256',
    projectId: 'crm-project-f8f9c',
    authDomain: 'crm-project-f8f9c.firebaseapp.com',
    storageBucket: 'crm-project-f8f9c.firebasestorage.app',
  );
}
